### ISSUE TITLE
Is this the repository for the NPM package with the same name?

### ISSUE THREAD

**Issue by jelhan** [peopledoc/ember-web-component-container#5]
Is this the repository for the NPM package with the same name? I'm a little bit confused as the NPM package seems to be newer than this repository. But both are maintained by you @xcambar. :confused:

I'm looking to bundle an ember app as a Web Component and this addon seems promising.

**Comment by xcambar** [comment]
Yes, it is the one :) 

The package served many internal purposes, so that may "explain" the unexpected state between the repository and the registry.

I'll update everything accordingly, but feel free to ask any question in the meantime. And thanks for #4

**Comment by jelhan** [comment]
> I'll update everything accordingly, but feel free to ask any question in the meantime. And thanks for #4

Thanks a lot in advance! To be honest I tried it out but directly faced #7. And then got confused. :laughing:
